### ISSUE TITLE
Add Price Chart

### ISSUE THREAD

**Issue by hussu010** [tnbCrow/tnbcrow-Minimal#6]
Add Price Chart below the "Recent Trades" section of the homepage of https://trade.tnbcrow.com/

Use https://www.chartjs.org/ to generate the chart.

Use the data of https://tnbcrow.pythonanywhere.com/market-chart endpoint.

Reward: 1000 TNBC

**Comment by FrostMegaByte** [comment]
What kind of chart do you expect? A line chart I suppose?

**Comment by hussu010** [comment]
@FrostMegaByte we're expecting a line chart with the price on the y-axis and date on the x-axis

**Comment by hydra91** [comment]
https://github.com/tnbCrow/tnbcrow-Minimal/pull/7
